/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mifinanza.views;

import com.mycompany.mifinanza.models.Categoria;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alumnadotarde
 */
public class CategoriasView extends javax.swing.JFrame {
    
    public CategoriasView() {
        initComponents();
        setTitle("Gestión de Categorías");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }
    
    public void mostrarCategorias(List<Categoria> lista) {
        String[] columnas = {"ID", "Nombre"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Hacer que la tabla no sea editable
            }
        };

        for (Categoria c : lista) {
            Object[] fila = {c.getId(), c.getNombre()};
            modelo.addRow(fila);
        }
        
        tblCategorias.setModel(modelo);
    }

    public JTable getTblCategorias() {
        return tblCategorias;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategorias = new javax.swing.JTable();
        
        JPanel panelFormulario = new JPanel();
        panelFormulario.setLayout(new BoxLayout(panelFormulario, BoxLayout.Y_AXIS));
        panelFormulario.setBorder(new EmptyBorder(10, 10, 10, 10));

        JPanel panelInput = new JPanel(new FlowLayout(FlowLayout.LEFT));
        jLabel1 = new JLabel("Nombre de Categoria:");
        txtNombre = new JTextField(20);
        panelInput.add(jLabel1);
        panelInput.add(txtNombre);
        
        JPanel panelBotones = new JPanel(new FlowLayout(FlowLayout.CENTER));
        btnGuardar = new JButton("Guardar");
        btnEliminar = new JButton("Eliminar");
        panelBotones.add(btnGuardar);
        panelBotones.add(btnEliminar);

        panelFormulario.add(panelInput);
        panelFormulario.add(panelBotones);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(panelFormulario, BorderLayout.NORTH);
        
        tblCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"ID", "Nombre"}
        ));
        jScrollPane1.setViewportView(tblCategorias);
        getContentPane().add(jScrollPane1, BorderLayout.CENTER);
        
        pack();
        
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnEliminar;
    private JButton btnGuardar;
    private JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private JTable tblCategorias;
    private JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}