/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mifinanza.views;

import com.mycompany.mifinanza.models.Cuenta;
import java.awt.*;
import java.util.List;
import javax.swing.*;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author alumnadotarde
 */
public class CuentasView extends javax.swing.JFrame {
    
    public CuentasView() {
        initComponents();
        setTitle("Gestión de Cuentas");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }
    
    public void mostrarCuentas(List<Cuenta> lista) {
        panelCuentas.removeAll();

        if (lista.isEmpty()) {
            panelCuentas.add(new JLabel("No hay cuentas registradas."));
        } else {
            for (Cuenta c : lista) {
                JPanel card = new JPanel(new BorderLayout(10, 10));
                card.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY),
                        new EmptyBorder(10, 15, 10, 15)
                ));
                card.setBackground(Color.WHITE);
                card.setMaximumSize(new Dimension(Integer.MAX_VALUE, 70));
                card.setPreferredSize(new Dimension(350, 70));

                JLabel lblNombre = new JLabel(c.getNombre());
                lblNombre.setFont(lblNombre.getFont().deriveFont(Font.BOLD, 14f));

                JLabel lblSaldo = new JLabel("$0.00 (Simulado)");
                lblSaldo.setForeground(Color.decode("#10B981"));
                lblSaldo.setFont(lblSaldo.getFont().deriveFont(Font.BOLD, 14f));

                card.add(lblNombre, BorderLayout.WEST);
                card.add(lblSaldo, BorderLayout.EAST);

                panelCuentas.add(card);
            }
        }

        panelCuentas.add(Box.createVerticalGlue());
        panelCuentas.revalidate();
        panelCuentas.repaint();
    }
    
    public JButton getBtnAnadirCuenta() {
        return btnAnadirCuenta;
    }

    public JTextField getTxtNombreCuenta() {
        return txtNombreCuenta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFormulario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreCuenta = new javax.swing.JTextField();
        btnAnadirCuenta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelCuentas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFormulario.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jLabel1.setText("Nombre de la Cuenta:");
        panelFormulario.add(jLabel1);
        
        txtNombreCuenta.setPreferredSize(new java.awt.Dimension(200, txtNombreCuenta.getPreferredSize().height));
        panelFormulario.add(txtNombreCuenta);

        btnAnadirCuenta.setText("Añadir Cuenta");
        panelFormulario.add(btnAnadirCuenta);

        getContentPane().add(panelFormulario, java.awt.BorderLayout.PAGE_START);

        panelCuentas.setLayout(new javax.swing.BoxLayout(panelCuentas, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(panelCuentas);
        jScrollPane1.setPreferredSize(new Dimension(400, 200));

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
        setMinimumSize(new Dimension(400, 300));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadirCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelCuentas;
    private javax.swing.JPanel panelFormulario;
    private javax.swing.JTextField txtNombreCuenta;
    // End of variables declaration//GEN-END:variables
}