/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mifinanza.views;

import com.mycompany.mifinanza.dao.CategoriaDAO;
import com.mycompany.mifinanza.dao.CuentaDAO;
import com.mycompany.mifinanza.dao.MetodoPagoDAO;
import com.mycompany.mifinanza.dao.TransaccionDAO;
import com.mycompany.mifinanza.models.Categoria;
import com.mycompany.mifinanza.models.Cuenta;
import com.mycompany.mifinanza.models.Gasto;
import com.mycompany.mifinanza.models.Ingreso;
import com.mycompany.mifinanza.models.MetodoPago;
import com.mycompany.mifinanza.utils.Sesion;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author federico
 */
public class FormularioTransaccionView extends javax.swing.JFrame {
    
    // Instancias de los DAOs para acceder a la BD
    private final CuentaDAO cuentaDAO = new CuentaDAO();
    private final CategoriaDAO categoriaDAO = new CategoriaDAO();
    private final MetodoPagoDAO metodoPagoDAO = new MetodoPagoDAO();
    private final TransaccionDAO transaccionDAO = new TransaccionDAO();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioTransaccionView.class.getName());

    /**
     * Creates new form FormularioTransaccionView
     */
    public FormularioTransaccionView() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        
        // Cargar los datos en los desplegables al iniciar
        cargarCombos();
        
        // Poner la fecha de hoy por defecto para ayudar al usuario
        String hoy = LocalDate.now().toString(); // Formato YYYY-MM-DD
        txtFechaGasto.setText(hoy);
        txtFechaIngreso.setText(hoy);
    }
    
    private void cargarCombos() {
        // 1. Obtener usuario actual para filtrar sus cuentas
        int idUsuario = Sesion.getUsuario().getId();
        
        // 2. Cargar Cuentas (Mismo modelo para ambos combos)
        List<Cuenta> cuentas = cuentaDAO.listarPorUsuario(idUsuario);
        // Usamos un array para el modelo del combo
        DefaultComboBoxModel modelCuentasGasto = new DefaultComboBoxModel(cuentas.toArray());
        DefaultComboBoxModel modelCuentasIngreso = new DefaultComboBoxModel(cuentas.toArray());
        
        cbCuentaGasto.setModel(modelCuentasGasto);
        cbCuentaIngreso.setModel(modelCuentasIngreso);
        
        // 3. Cargar Categorías
        List<Categoria> categorias = categoriaDAO.listar();
        DefaultComboBoxModel modelCatGasto = new DefaultComboBoxModel(categorias.toArray());
        DefaultComboBoxModel modelCatIngreso = new DefaultComboBoxModel(categorias.toArray());
        
        cbCategoriaGasto.setModel(modelCatGasto);
        cbCategoriaIngreso.setModel(modelCatIngreso);
        
        // 4. Cargar Métodos de Pago (Solo para Gasto)
        List<MetodoPago> metodos = metodoPagoDAO.listar();
        cbMetodoPago.setModel(new DefaultComboBoxModel(metodos.toArray()));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtMontoGasto = new javax.swing.JTextField();
        txtDescGasto = new javax.swing.JTextField();
        txtComercio = new javax.swing.JTextField();
        cbCuentaGasto = new javax.swing.JComboBox<>();
        cbCategoriaGasto = new javax.swing.JComboBox<>();
        cbMetodoPago = new javax.swing.JComboBox<>();
        txtFechaGasto = new javax.swing.JTextField();
        btnGuardarGasto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtMontoIngreso = new javax.swing.JTextField();
        txtDescIngreso = new javax.swing.JTextField();
        txtFuente = new javax.swing.JTextField();
        cbCuentaIngreso = new javax.swing.JComboBox<>();
        cbCategoriaIngreso = new javax.swing.JComboBox<>();
        txtFechaIngreso = new javax.swing.JTextField();
        btnGuardarIngreso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtMontoGasto.setText("Monto Gasto");
        txtMontoGasto.addActionListener(this::txtMontoGastoActionPerformed);

        txtDescGasto.setText("Descripcion");

        txtComercio.setText("Comercio");

        cbCuentaGasto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCuentaGasto.addActionListener(this::cbCuentaGastoActionPerformed);

        cbCategoriaGasto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtFechaGasto.setText("Fecha Gasto");

        btnGuardarGasto.setText("Guardar gasto");
        btnGuardarGasto.addActionListener(this::btnGuardarGastoActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMontoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComercio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCuentaGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCategoriaGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarGasto))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMontoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtComercio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCuentaGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCategoriaGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarGasto)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar Gasto", jPanel1);

        txtMontoIngreso.setText("Monto Ingreso");

        txtDescIngreso.setText("Descripcion");

        txtFuente.setText("Fuente");

        cbCuentaIngreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbCategoriaIngreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtFechaIngreso.setText("Fecha ingreso");

        btnGuardarIngreso.setText("Guardar Ingreso");
        btnGuardarIngreso.addActionListener(this::btnGuardarIngresoActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMontoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCuentaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCategoriaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarIngreso))
                .addGap(0, 173, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMontoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCuentaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCategoriaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarIngreso)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar Ingreso", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoGastoActionPerformed

    private void cbCuentaGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCuentaGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCuentaGastoActionPerformed

    private void btnGuardarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarGastoActionPerformed
        try {
            // 1. Validar y Obtener datos básicos
            double monto = Double.parseDouble(txtMontoGasto.getText());
            String desc = txtDescGasto.getText();
            String comercio = txtComercio.getText();
            String fechaStr = txtFechaGasto.getText(); // Esperamos YYYY-MM-DD
            
            // Convertir String a Timestamp (añadiendo hora 00:00:00)
            Timestamp fecha = Timestamp.valueOf(fechaStr + " 00:00:00");

            // 2. Obtener objetos seleccionados de los ComboBox
            Cuenta cuentaSelec = (Cuenta) cbCuentaGasto.getSelectedItem();
            Categoria catSelec = (Categoria) cbCategoriaGasto.getSelectedItem();
            MetodoPago metodoSelec = (MetodoPago) cbMetodoPago.getSelectedItem();

            if (cuentaSelec == null || catSelec == null || metodoSelec == null) {
                JOptionPane.showMessageDialog(this, "Faltan datos por seleccionar.");
                return;
            }

            // 3. Crear el objeto Gasto
            Gasto nuevoGasto = new Gasto(
                monto, 
                fecha, 
                desc, 
                comercio, 
                cuentaSelec.getId(), 
                metodoSelec.getId(), 
                catSelec.getId(), 
                Sesion.getUsuario().getId()
            );

            // 4. Guardar en BD
            if (transaccionDAO.registrarGasto(nuevoGasto)) {
                JOptionPane.showMessageDialog(this, "¡Gasto registrado y saldo actualizado!");
                this.dispose(); // Cerrar ventana
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar el gasto.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El monto debe ser un número válido.");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto (Use YYYY-MM-DD).");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error desconocido: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarGastoActionPerformed

    private void btnGuardarIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarIngresoActionPerformed
        try {
            double monto = Double.parseDouble(txtMontoIngreso.getText());
            String desc = txtDescIngreso.getText();
            String fuente = txtFuente.getText();
            Timestamp fecha = Timestamp.valueOf(txtFechaIngreso.getText() + " 00:00:00");

            Cuenta cuentaSelec = (Cuenta) cbCuentaIngreso.getSelectedItem();
            Categoria catSelec = (Categoria) cbCategoriaIngreso.getSelectedItem();

            if (cuentaSelec == null || catSelec == null) {
                JOptionPane.showMessageDialog(this, "Selecciona cuenta y categoría.");
                return;
            }

            Ingreso nuevoIngreso = new Ingreso(
                monto,
                fecha,
                desc,
                fuente,
                cuentaSelec.getId(),
                catSelec.getId(),
                Sesion.getUsuario().getId()
            );

            if (transaccionDAO.registrarIngreso(nuevoIngreso)) {
                JOptionPane.showMessageDialog(this, "¡Ingreso registrado! Dinero añadido.");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar ingreso.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en los datos: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarIngresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormularioTransaccionView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarGasto;
    private javax.swing.JButton btnGuardarIngreso;
    private javax.swing.JComboBox<String> cbCategoriaGasto;
    private javax.swing.JComboBox<String> cbCategoriaIngreso;
    private javax.swing.JComboBox<String> cbCuentaGasto;
    private javax.swing.JComboBox<String> cbCuentaIngreso;
    private javax.swing.JComboBox<String> cbMetodoPago;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtComercio;
    private javax.swing.JTextField txtDescGasto;
    private javax.swing.JTextField txtDescIngreso;
    private javax.swing.JTextField txtFechaGasto;
    private javax.swing.JTextField txtFechaIngreso;
    private javax.swing.JTextField txtFuente;
    private javax.swing.JTextField txtMontoGasto;
    private javax.swing.JTextField txtMontoIngreso;
    // End of variables declaration//GEN-END:variables
}
