/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mifinanza.views;

import java.time.LocalDate;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author federico
 */
public class FormularioTransaccionView extends javax.swing.JFrame {
    
    public FormularioTransaccionView() {
        initComponents();
        setTitle("Registrar Transacción");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        
        String hoy = LocalDate.now().toString();
        txtFechaGasto.setText(hoy);
        txtFechaIngreso.setText(hoy);
    }
    
    // --- Setters para los ComboBox ---
    public void setCuentasGastoModel(DefaultComboBoxModel model) { cbCuentaGasto.setModel(model); }
    public void setCuentasIngresoModel(DefaultComboBoxModel model) { cbCuentaIngreso.setModel(model); }
    public void setCategoriasGastoModel(DefaultComboBoxModel model) { cbCategoriaGasto.setModel(model); }
    public void setCategoriasIngresoModel(DefaultComboBoxModel model) { cbCategoriaIngreso.setModel(model); }
    public void setMetodosPagoModel(DefaultComboBoxModel model) { cbMetodoPago.setModel(model); }

    // --- Getters para todos los componentes del formulario ---
    public JButton getBtnGuardarGasto() { return btnGuardarGasto; }
    public JButton getBtnGuardarIngreso() { return btnGuardarIngreso; }
    public JComboBox getCbCategoriaGasto() { return cbCategoriaGasto; }
    public JComboBox getCbCategoriaIngreso() { return cbCategoriaIngreso; }
    public JComboBox getCbCuentaGasto() { return cbCuentaGasto; }
    public JComboBox getCbCuentaIngreso() { return cbCuentaIngreso; }
    public JComboBox getCbMetodoPago() { return cbMetodoPago; }
    public JTextField getTxtComercio() { return txtComercio; }
    public JTextField getTxtDescGasto() { return txtDescGasto; }
    public JTextField getTxtDescIngreso() { return txtDescIngreso; }
    public JTextField getTxtFechaGasto() { return txtFechaGasto; }
    public JTextField getTxtFechaIngreso() { return txtFechaIngreso; }
    public JTextField getTxtFuente() { return txtFuente; }
    public JTextField getTxtMontoGasto() { return txtMontoGasto; }
    public JTextField getTxtMontoIngreso() { return txtMontoIngreso; }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtMontoGasto = new javax.swing.JTextField();
        txtDescGasto = new javax.swing.JTextField();
        txtComercio = new javax.swing.JTextField();
        cbCuentaGasto = new javax.swing.JComboBox<>();
        cbCategoriaGasto = new javax.swing.JComboBox<>();
        cbMetodoPago = new javax.swing.JComboBox<>();
        txtFechaGasto = new javax.swing.JTextField();
        btnGuardarGasto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtMontoIngreso = new javax.swing.JTextField();
        txtDescIngreso = new javax.swing.JTextField();
        txtFuente = new javax.swing.JTextField();
        cbCuentaIngreso = new javax.swing.JComboBox<>();
        cbCategoriaIngreso = new javax.swing.JComboBox<>();
        txtFechaIngreso = new javax.swing.JTextField();
        btnGuardarIngreso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtMontoGasto.setBorder(javax.swing.BorderFactory.createTitledBorder("Monto Gasto"));

        txtDescGasto.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));

        txtComercio.setBorder(javax.swing.BorderFactory.createTitledBorder("Comercio"));

        cbCuentaGasto.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuenta"));

        cbCategoriaGasto.setBorder(javax.swing.BorderFactory.createTitledBorder("Categoría"));

        cbMetodoPago.setBorder(javax.swing.BorderFactory.createTitledBorder("Método de Pago"));

        txtFechaGasto.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha (YYYY-MM-DD)"));

        btnGuardarGasto.setText("Guardar Gasto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardarGasto)
                    .addComponent(txtMontoGasto)
                    .addComponent(txtDescGasto)
                    .addComponent(txtComercio)
                    .addComponent(cbCuentaGasto, 0, 250, Short.MAX_VALUE)
                    .addComponent(cbCategoriaGasto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbMetodoPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFechaGasto))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMontoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtComercio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCuentaGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCategoriaGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardarGasto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar Gasto", jPanel1);

        txtMontoIngreso.setBorder(javax.swing.BorderFactory.createTitledBorder("Monto Ingreso"));

        txtDescIngreso.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));

        txtFuente.setBorder(javax.swing.BorderFactory.createTitledBorder("Fuente"));

        cbCuentaIngreso.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuenta"));

        cbCategoriaIngreso.setBorder(javax.swing.BorderFactory.createTitledBorder("Categoría"));

        txtFechaIngreso.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha (YYYY-MM-DD)"));

        btnGuardarIngreso.setText("Guardar Ingreso");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardarIngreso)
                    .addComponent(txtMontoIngreso)
                    .addComponent(txtDescIngreso)
                    .addComponent(txtFuente)
                    .addComponent(cbCuentaIngreso, 0, 250, Short.MAX_VALUE)
                    .addComponent(cbCategoriaIngreso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFechaIngreso))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMontoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCuentaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCategoriaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardarIngreso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar Ingreso", jPanel2);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);
        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarGasto;
    private javax.swing.JButton btnGuardarIngreso;
    private javax.swing.JComboBox<String> cbCategoriaGasto;
    private javax.swing.JComboBox<String> cbCategoriaIngreso;
    private javax.swing.JComboBox<String> cbCuentaGasto;
    private javax.swing.JComboBox<String> cbCuentaIngreso;
    private javax.swing.JComboBox<String> cbMetodoPago;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtComercio;
    private javax.swing.JTextField txtDescGasto;
    private javax.swing.JTextField txtDescIngreso;
    private javax.swing.JTextField txtFechaGasto;
    private javax.swing.JTextField txtFechaIngreso;
    private javax.swing.JTextField txtFuente;
    private javax.swing.JTextField txtMontoGasto;
    private javax.swing.JTextField txtMontoIngreso;
    // End of variables declaration//GEN-END:variables
}
