/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mifinanza.views;

import com.mycompany.mifinanza.models.Presupuesto;
import java.awt.*;
import java.util.List;
import javax.swing.*;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author federico
 */
public class PresupuestosView extends javax.swing.JFrame {

    public PresupuestosView() {
        initComponents();
        setTitle("Mis Presupuestos");
        this.setSize(800, 600);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }

    public void mostrarPresupuestos(List<Presupuesto> lista) {
        panelListado.removeAll();

        if (lista.isEmpty()) {
            panelListado.add(new JLabel("No tienes presupuestos activos. ¡Crea uno!"));
        } else {
            for (Presupuesto p : lista) {
                JPanel card = new JPanel();
                card.setLayout(new BoxLayout(card, BoxLayout.Y_AXIS));
                card.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY),
                        new EmptyBorder(15, 15, 15, 15)
                ));
                card.setBackground(Color.WHITE);
                card.setMaximumSize(new Dimension(Integer.MAX_VALUE, 100));

                JPanel headerPanel = new JPanel(new BorderLayout());
                headerPanel.setBackground(Color.WHITE);
                
                JLabel lblCategoria = new JLabel(p.getNombreCategoria());
                lblCategoria.setFont(new Font("Segoe UI", Font.BOLD, 16));
                
                JLabel lblFechas = new JLabel(p.getFechaInicio() + " al " + p.getFechaFin());
                lblFechas.setForeground(Color.GRAY);
                
                headerPanel.add(lblCategoria, BorderLayout.WEST);
                headerPanel.add(lblFechas, BorderLayout.EAST);
                
                JProgressBar progressBar = new JProgressBar(0, (int) p.getMontoTotal());
                progressBar.setValue((int) p.getMontoActual());
                progressBar.setStringPainted(true);
                
                if (p.getMontoActual() > p.getMontoTotal()) {
                    progressBar.setForeground(Color.RED);
                    progressBar.setString("¡EXCEDIDO! " + String.format("%.2f", p.getMontoActual()) + " / " + String.format("%.2f", p.getMontoTotal()));
                } else {
                    progressBar.setForeground(new Color(50, 205, 50));
                    progressBar.setString("Gastado: " + String.format("%.2f", p.getMontoActual()) + " / " + String.format("%.2f", p.getMontoTotal()));
                }

                card.add(headerPanel);
                card.add(Box.createVerticalStrut(10));
                card.add(progressBar);
                
                panelListado.add(card);
            }
        }
        
        panelListado.add(Box.createVerticalGlue());
        panelListado.revalidate();
        panelListado.repaint();
    }
    
    public JButton getBtnCrear() {
        return btnCrear;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelListado = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Mis Presupuestos");
        jPanel1.add(jLabel1);

        btnCrear.setText("Crear Nuevo Presupuesto");
        jPanel1.add(btnCrear);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        panelListado.setBackground(new java.awt.Color(255, 255, 255));
        panelListado.setLayout(new javax.swing.BoxLayout(panelListado, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(panelListado);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelListado;
    // End of variables declaration//GEN-END:variables
}